### Post 60
**Post URL**: /t/tds-official-project1-discrepencies/171141/60
- **ID**: 612479
- **Author**: Jivraj Singh Shekhawat (Jivraj)
- **Created At**: 2025-03-29T06:39:00.764Z
- **Reply To**: Post 50 (Ritwika Dutta , 22f2001389)
- **Content**:  
  Hi <a class="mention" href="/u/22f2001389">@22f2001389</a>
<pre data-code-wrap="Traceback"><code class="lang-Traceback">  File "/app/app.py", line 4, in &lt;module&gt;
    from tasksA import *
ModuleNotFoundError: No module named 'tasksA'
</code></pre>
The error occurs because Python cannot find the <code>tasksA</code> module. This is due to the file not existing, not being in the correct directory.
Kind regards
- **Reactions**: None
- **Post Number**: 60

